### ISSUE TITLE
Broken link: https://nips.be in the resources page

### ISSUE THREAD

**Issue by Sebastix** [nostrdesignguide/nostrdesignguide.github.io#12]
Found a broken link on https://nostrdesign.org/docs/resources

* https://nips.be/

Maybe this is a better overview: https://nostrdata.github.io/kinds/ but is also link to the broken nips.be URL.

**Comment by weex** [comment]
I'd argue to remove the Development section instead. A good development section would now have dozens of links. Maybe a single link to https://github.com/aljazceru/awesome-nostr ?

**Comment by Sebastix** [comment]
> I'd argue to remove the Development section instead. A good development section would now have dozens of links. Maybe a single link to https://github.com/aljazceru/awesome-nostr ?

That's something to discuss in another issue I think.

I noticed the link is working again and I also discovered another good resource on this: https://nostr-nips.com/#event-kinds

**Comment by weex** [comment]
I don't think it warrants an issue, it was just a suggestion as to a possible solution. It was working for me so perhaps this is solved.
